const ROLES = {
  NATIONAL_ADMIN: 'NATIONAL_ADMIN',
  STATE_ADMIN: 'STATE_ADMIN',
  DISTRICT_OFFICER: 'DISTRICT_OFFICER',
  PHC_STAFF: 'PHC_STAFF',
};

const ROLE_VALUES = Object.values(ROLES);

export { ROLES, ROLE_VALUES };
