const ROLES = {
  NATIONAL_ADMIN: 'NATIONAL_ADMIN',
  STATE_ADMIN: 'STATE_ADMIN',
  DISTRICT_OFFICER: 'DISTRICT_OFFICER',
  PHC_STAFF: 'PHC_STAFF',
};

const ROLE_LABEL = {
  NATIONAL_ADMIN: 'NATIONAL ADMIN',
  STATE_ADMIN: 'STATE ADMIN',
  DISTRICT_OFFICER: 'DISTRICT OFFICER',
  PHC_STAFF: 'PHC STAFF',
};

const ROLE_HOME = {
  NATIONAL_ADMIN: '/national',
  STATE_ADMIN: '/state',
  DISTRICT_OFFICER: '/district',
  PHC_STAFF: '/phc',
};

export { ROLES, ROLE_LABEL, ROLE_HOME };
